### ISSUE TITLE
The Angle of the Laser

### ISSUE THREAD

**Issue by George-Gauvierre6** [TeamTseb/FasterThanBullets#1]
The laser is only able to shoot upwards, we need to establish a variable that shoots the laser at the degree at which our starship is at.

**Comment by J0hnMace** [comment]
Make a variable that uses 

`   this.newPos = function() {

```
    this.angle += this.moveAngle * Math.PI / 180;
    this.x += this.speed * Math.sin(this.angle);
    this.y -= this.speed * Math.cos(this.angle);

}`
```
