### ISSUE TITLE
Color of the Navbar

### ISSUE THREAD

**Issue by George-Gauvierre6** [TeamTseb/FasterThanBullets#13]
On our website (homepage.html) we have a very dark color scheme inherent to BootStrap.  The (seemingly) simplest way to change this is to add to modifications.css, which is imported with the boot strap, there we should be able to change the color of the navbar or at least the header.

**Comment by J0hnMace** [comment]
Let me know when you finish this.

**Comment by George-Gauvierre6** [comment]
Fixed
